// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// QuizsColumns holds the columns for the "quizs" table.
	QuizsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "problem", Type: field.TypeString, Default: "unknown"},
		{Name: "answer", Type: field.TypeString, Default: "unknown"},
	}
	// QuizsTable holds the schema information for the "quizs" table.
	QuizsTable = &schema.Table{
		Name:       "quizs",
		Columns:    QuizsColumns,
		PrimaryKey: []*schema.Column{QuizsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		QuizsTable,
	}
)

func init() {
}
