// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sakuradaman/quiz/pkg/ent/predicate"
	"github.com/sakuradaman/quiz/pkg/ent/quiz"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeQuiz = "Quiz"
)

// QuizMutation represents an operation that mutates the Quiz nodes in the graph.
type QuizMutation struct {
	config
	op            Op
	typ           string
	id            *int
	problem       *string
	answer        *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Quiz, error)
	predicates    []predicate.Quiz
}

var _ ent.Mutation = (*QuizMutation)(nil)

// quizOption allows management of the mutation configuration using functional options.
type quizOption func(*QuizMutation)

// newQuizMutation creates new mutation for the Quiz entity.
func newQuizMutation(c config, op Op, opts ...quizOption) *QuizMutation {
	m := &QuizMutation{
		config:        c,
		op:            op,
		typ:           TypeQuiz,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withQuizID sets the ID field of the mutation.
func withQuizID(id int) quizOption {
	return func(m *QuizMutation) {
		var (
			err   error
			once  sync.Once
			value *Quiz
		)
		m.oldValue = func(ctx context.Context) (*Quiz, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Quiz.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withQuiz sets the old Quiz of the mutation.
func withQuiz(node *Quiz) quizOption {
	return func(m *QuizMutation) {
		m.oldValue = func(context.Context) (*Quiz, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m QuizMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m QuizMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *QuizMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *QuizMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Quiz.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetProblem sets the "problem" field.
func (m *QuizMutation) SetProblem(s string) {
	m.problem = &s
}

// Problem returns the value of the "problem" field in the mutation.
func (m *QuizMutation) Problem() (r string, exists bool) {
	v := m.problem
	if v == nil {
		return
	}
	return *v, true
}

// OldProblem returns the old "problem" field's value of the Quiz entity.
// If the Quiz object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *QuizMutation) OldProblem(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProblem is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProblem requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProblem: %w", err)
	}
	return oldValue.Problem, nil
}

// ResetProblem resets all changes to the "problem" field.
func (m *QuizMutation) ResetProblem() {
	m.problem = nil
}

// SetAnswer sets the "answer" field.
func (m *QuizMutation) SetAnswer(s string) {
	m.answer = &s
}

// Answer returns the value of the "answer" field in the mutation.
func (m *QuizMutation) Answer() (r string, exists bool) {
	v := m.answer
	if v == nil {
		return
	}
	return *v, true
}

// OldAnswer returns the old "answer" field's value of the Quiz entity.
// If the Quiz object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *QuizMutation) OldAnswer(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAnswer is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAnswer requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAnswer: %w", err)
	}
	return oldValue.Answer, nil
}

// ResetAnswer resets all changes to the "answer" field.
func (m *QuizMutation) ResetAnswer() {
	m.answer = nil
}

// Where appends a list predicates to the QuizMutation builder.
func (m *QuizMutation) Where(ps ...predicate.Quiz) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the QuizMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *QuizMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Quiz, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *QuizMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *QuizMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Quiz).
func (m *QuizMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *QuizMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.problem != nil {
		fields = append(fields, quiz.FieldProblem)
	}
	if m.answer != nil {
		fields = append(fields, quiz.FieldAnswer)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *QuizMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case quiz.FieldProblem:
		return m.Problem()
	case quiz.FieldAnswer:
		return m.Answer()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *QuizMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case quiz.FieldProblem:
		return m.OldProblem(ctx)
	case quiz.FieldAnswer:
		return m.OldAnswer(ctx)
	}
	return nil, fmt.Errorf("unknown Quiz field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *QuizMutation) SetField(name string, value ent.Value) error {
	switch name {
	case quiz.FieldProblem:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProblem(v)
		return nil
	case quiz.FieldAnswer:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAnswer(v)
		return nil
	}
	return fmt.Errorf("unknown Quiz field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *QuizMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *QuizMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *QuizMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Quiz numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *QuizMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *QuizMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *QuizMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Quiz nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *QuizMutation) ResetField(name string) error {
	switch name {
	case quiz.FieldProblem:
		m.ResetProblem()
		return nil
	case quiz.FieldAnswer:
		m.ResetAnswer()
		return nil
	}
	return fmt.Errorf("unknown Quiz field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *QuizMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *QuizMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *QuizMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *QuizMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *QuizMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *QuizMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *QuizMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Quiz unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *QuizMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Quiz edge %s", name)
}
