// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sakuradaman/quiz/pkg/ent/quiz"
)

// QuizCreate is the builder for creating a Quiz entity.
type QuizCreate struct {
	config
	mutation *QuizMutation
	hooks    []Hook
}

// SetProblem sets the "problem" field.
func (qc *QuizCreate) SetProblem(s string) *QuizCreate {
	qc.mutation.SetProblem(s)
	return qc
}

// SetNillableProblem sets the "problem" field if the given value is not nil.
func (qc *QuizCreate) SetNillableProblem(s *string) *QuizCreate {
	if s != nil {
		qc.SetProblem(*s)
	}
	return qc
}

// SetAnswer sets the "answer" field.
func (qc *QuizCreate) SetAnswer(s string) *QuizCreate {
	qc.mutation.SetAnswer(s)
	return qc
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (qc *QuizCreate) SetNillableAnswer(s *string) *QuizCreate {
	if s != nil {
		qc.SetAnswer(*s)
	}
	return qc
}

// Mutation returns the QuizMutation object of the builder.
func (qc *QuizCreate) Mutation() *QuizMutation {
	return qc.mutation
}

// Save creates the Quiz in the database.
func (qc *QuizCreate) Save(ctx context.Context) (*Quiz, error) {
	qc.defaults()
	return withHooks(ctx, qc.sqlSave, qc.mutation, qc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (qc *QuizCreate) SaveX(ctx context.Context) *Quiz {
	v, err := qc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qc *QuizCreate) Exec(ctx context.Context) error {
	_, err := qc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qc *QuizCreate) ExecX(ctx context.Context) {
	if err := qc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (qc *QuizCreate) defaults() {
	if _, ok := qc.mutation.Problem(); !ok {
		v := quiz.DefaultProblem
		qc.mutation.SetProblem(v)
	}
	if _, ok := qc.mutation.Answer(); !ok {
		v := quiz.DefaultAnswer
		qc.mutation.SetAnswer(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qc *QuizCreate) check() error {
	if _, ok := qc.mutation.Problem(); !ok {
		return &ValidationError{Name: "problem", err: errors.New(`ent: missing required field "Quiz.problem"`)}
	}
	if _, ok := qc.mutation.Answer(); !ok {
		return &ValidationError{Name: "answer", err: errors.New(`ent: missing required field "Quiz.answer"`)}
	}
	return nil
}

func (qc *QuizCreate) sqlSave(ctx context.Context) (*Quiz, error) {
	if err := qc.check(); err != nil {
		return nil, err
	}
	_node, _spec := qc.createSpec()
	if err := sqlgraph.CreateNode(ctx, qc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	qc.mutation.id = &_node.ID
	qc.mutation.done = true
	return _node, nil
}

func (qc *QuizCreate) createSpec() (*Quiz, *sqlgraph.CreateSpec) {
	var (
		_node = &Quiz{config: qc.config}
		_spec = sqlgraph.NewCreateSpec(quiz.Table, sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt))
	)
	if value, ok := qc.mutation.Problem(); ok {
		_spec.SetField(quiz.FieldProblem, field.TypeString, value)
		_node.Problem = value
	}
	if value, ok := qc.mutation.Answer(); ok {
		_spec.SetField(quiz.FieldAnswer, field.TypeString, value)
		_node.Answer = value
	}
	return _node, _spec
}

// QuizCreateBulk is the builder for creating many Quiz entities in bulk.
type QuizCreateBulk struct {
	config
	err      error
	builders []*QuizCreate
}

// Save creates the Quiz entities in the database.
func (qcb *QuizCreateBulk) Save(ctx context.Context) ([]*Quiz, error) {
	if qcb.err != nil {
		return nil, qcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(qcb.builders))
	nodes := make([]*Quiz, len(qcb.builders))
	mutators := make([]Mutator, len(qcb.builders))
	for i := range qcb.builders {
		func(i int, root context.Context) {
			builder := qcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuizMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, qcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, qcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, qcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (qcb *QuizCreateBulk) SaveX(ctx context.Context) []*Quiz {
	v, err := qcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qcb *QuizCreateBulk) Exec(ctx context.Context) error {
	_, err := qcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qcb *QuizCreateBulk) ExecX(ctx context.Context) {
	if err := qcb.Exec(ctx); err != nil {
		panic(err)
	}
}
