// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/sakuradaman/quiz/pkg/ent/quiz"
	"github.com/sakuradaman/quiz/pkg/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	quizFields := schema.Quiz{}.Fields()
	_ = quizFields
	// quizDescProblem is the schema descriptor for problem field.
	quizDescProblem := quizFields[0].Descriptor()
	// quiz.DefaultProblem holds the default value on creation for the problem field.
	quiz.DefaultProblem = quizDescProblem.Default.(string)
	// quizDescAnswer is the schema descriptor for answer field.
	quizDescAnswer := quizFields[1].Descriptor()
	// quiz.DefaultAnswer holds the default value on creation for the answer field.
	quiz.DefaultAnswer = quizDescAnswer.Default.(string)
}
